### ISSUE TITLE
Add chromecast support

### ISSUE THREAD

**Issue by Rediwed** [quanglam2807/appifier#20] opened 2017-01-15 22:43 UTC
Maybe it'd be a great idea to add chromecast/airplay support. As WebCatalog build on chromium I'd think there'd be the possibility of adding such support?

Might be a little more of a long-term feature request though.

**Comment by quanglam2807** [comment] 2017-01-16 03:09
@Rediwed It seems possible :) https://github.com/GPMDP/electron-chromecast

**Comment by quanglam2807** [comment] 2017-01-16 03:18
544a3f0, Cast icon appears but I'm not sure if it works or not because I don't have a Chromecast :)

**Comment by Rediwed** [comment] 2017-01-16 11:48
I would love to test it, but I am not able to build the current source.

As i've said, I am not a developer (but am tech-savvy). Could you send me a build or tell me what's wrong?

> npm ERR! Darwin 16.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! WebCatalog@2.7.2 compile: `cross-env NODE_ENV=production webpack -p`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the WebCatalog@2.7.2 compile script 'cross-env NODE_ENV=production webpack -p'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the WebCatalog package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     cross-env NODE_ENV=production webpack -p
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs WebCatalog
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls WebCatalog
> npm ERR! There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/Cadat/Desktop/desktop-master/npm-debug.log
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by quanglam2807** [comment] 2017-01-16 18:43
@Rediwed You need to run `yarn` first. But new build is coming soon so don't worry.

**Comment by Rediwed** [comment] 2017-01-16 20:13
Hmm, I did run yarn first..

**Comment by quanglam2807** [comment] 2017-01-16 22:53
@Rediwed, weird. The error log says so: 
```
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by Rediwed** [comment] 2017-01-16 23:09
It replies with:
yarn install v0.18.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
success Nothing to install.
✨  Done in 0.21s.

**Comment by quanglam2807** [comment] 2017-01-16 23:10
@Rediwed From which folder did you run the command?

**Comment by Rediwed** [comment] 2017-01-17 14:20
Were you able to implement this feature?

**Comment by quanglam2807** [comment] 2017-01-17 19:01
@Rediwed I implemented it. But let's wait until you can test it with the next update. If it doesn't work as expected, I'll reopen this issue.

**Comment by quanglam2807** [comment] 2017-01-18 19:14
@Rediwed it's up now with 2.8.0

**Comment by Rediwed** [comment] 2017-01-18 22:33
I tried it, no chromecast icon on this side.. Does it need to be set up somehow?

**Comment by quanglam2807** [comment] 2017-01-18 22:35
@Rediwed What app are you using? Chromecast icon appears in Google Play Music for me.

**Comment by Rediwed** [comment] 2017-01-18 22:43
Both Youtube and netflix. Let me try Play music..

**Comment by Rediwed** [comment] 2017-01-18 22:48
Sweet!! Chromecast support works perfectly in Play Music!!

I want to try it in Spotify, but am not able to log in anymore (using facebook auth).

**Comment by quanglam2807** [comment] 2017-01-18 22:49
@Rediwed it seems like it only works with some applications. As I understand, WebCatalog use Cast v2 while Google has already released v3. Google Play Music works because Google still uses the old version.

**Comment by quanglam2807** [comment] 2017-01-18 22:50
GPMDP/electron-chromecast#40
electron/electron#7024

**Comment by Rediwed** [comment] 2017-01-18 23:00
Hmm, so v2 has been deprecated for services that have been updated to v3...

V3 is meant for increased ease of use and reliability, might not be hard for them to implement. Until such time we have to wait though..

Though @evancohen mentioned (electron/electron#7024) that v3 now built into chromium, shouldn't there be cross-compatibility as WebCatalog runs on chromium?

**Comment by Rediwed** [comment] 2017-01-18 23:14
So apparently, the cast funcitonality IS build into chromium.. Though the discory functionality is excluded, so it's basically useles!

**Comment by quanglam2807** [comment] 2017-01-19 02:43
@Rediwed Yup, so this is the best we have at the moment. I will close the issue until we have something new to resolve it.

**Closed as completed by quanglam2807** 2017-01-19 02:43 UTC
Labels: enhancement

**Comment by MarshallOfSound** [comment] 2017-02-18 15:01
Someone pinged me this issue so I might be able to provide some insight into this.

The `electron-chromecast` module was designed purely to work with Google Play Music.  Some other sites work as well but the ChromeCast API isn't fully implemented.  I wouldn't be suprised (given the two apps listed that fail are video based apps) that we are missing API's specific to the `video` capability.

**Comment by quanglam2807** [comment] 2017-02-19 21:14
@MarshallOfSound Thank you very much +1. At least, it works with Google Play Music.
