### ISSUE TITLE
Cannot update apps

### ISSUE THREAD

**Issue by nyex** [quanglam2807/appifier#248] opened 2018-01-13 22:17 UTC
Ubuntu 17.10
WebCatalog 9.2.1 (but was the same in previous versions).

The console says:

```
Error: EEXIST: file already exists, link '/tmp/Amazon Kindle-linux-x64' -> '/home/olivia/.webcatalog/apps/Amazon Kindle-linux-x64'
actions.js:77 Error: Installing failed.
    at EventEmitter.o (install-app-async.js:23)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)
```

(The same with any app, though)

I can install new apps with no problem. If I uninstall one of these that are requesting for an update and then install again, it shows a different error: 

```
Error: EEXIST: file already exists, link '/tmp/electron-packager/linux-x64/Amazon Kindle-linux-x64' -> '/tmp/Amazon Kindle-linux-x64'
actions.js:47 Error: Installing failed.
    at EventEmitter.o (install-app-async.js:23)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)
```
Of course it installs fine if I just go and delete the folder in /tmp.

Not so critical since I can simply keep using the apps without updating, but thought I'd report it anyway.

**Comment by quanglam2807** [comment] 2018-01-13 22:41
It's odd. `electron-packager` is supposed to overwrite the folder: https://github.com/quanglam2807/webcatalog/blob/master/packages/appifier/src/index.js#L29

**Comment by lparsons** [comment] 2018-01-16 16:56
I'm running into a similar issue. I didn't get the error message the first time, but I did uninstall the app (Todoist) I was unable to update (since nothing works for me right now anyway due to previous bug). However, now webcatalog always shows Todoist as installed when I start up webcatalog (even if I've previously uninstalled). I tried remove the tmp folder, and that didn't help. So I tried "updating" the uninstalled app, that failed (predictably):
```
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/WebCatalog/resources/app-update.yml'
    at /opt/WebCatalog/resources/app/node_modules/electron-updater/src/AppUpdater.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/WebCatalog/resources/app/node_modules/electron-updater/out/AppUpdater.js:379:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/WebCatalog/resources/app/node_modules/electron-updater/src/AppUpdater.ts:124:43)
    at Lazy.get value [as value] (/opt/WebCatalog/resources/app/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/WebCatalog/resources/app/node_modules/electron-updater/src/AppUpdater.ts:272:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/WebCatalog/resources/app/node_modules/electron-updater/out/AppUpdater.js:337:11)
    at /opt/WebCatalog/resources/app/node_modules/electron-updater/src/AppUpdater.ts:255:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/WebCatalog/resources/app/node_modules/electron-updater/out/AppUpdater.js:291:11)
    at AppImageUpdater.checkForUpdates (/opt/WebCatalog/resources/app/node_modules/electron-updater/src/AppUpdater.ts:204:35)
    at EventEmitter.ipcMain.on (/opt/WebCatalog/resources/app/build/listeners/updater.js:9:17)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/WebCatalog/resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
Packaging app for platform linux x64 using electron v1.7.10
```

I'm still unable to install the app, however, I get the error "We're sorry. WebCatalog has failed to install Todoist.". But there is no output on the console except for `Packaging app for platform linux x64 using electron v1.7.10`

**Comment by quanglam2807** [comment] 2018-01-16 17:06
I will need to debug this. This is odd because I didn't change anything in the app generating code.

**Comment by toyg** [comment] 2018-01-18 02:06
Not sure if related, but on Windows my WebCatalog seems stuck with an update that never runs. This makes it impossible to run new apps, since their launching button is stuck on "Update". I find it weird also that I installed WC a week ago but somehow it's marked as 9.0, whereas I believe it should have been 9.2...

![capture](https://user-images.githubusercontent.com/219614/35077237-fa926b92-fbf3-11e7-8630-6359f6dec345.PNG)

**Comment by quanglam2807** [comment] 2018-01-18 02:19
@toyg It's not related to this issue but you should just download the file directly from the website. The library `electron-builder` (which WC relies on) recently makes some major changes so I think it's the cause.

**Comment by jlandes** [comment] 2018-01-30 19:08
I'm running into the same issue that none of my apps will update. I'm running Linux Mint 18.3 and WebCatalog 9.3.1.

**Comment by quanglam2807** [comment] 2018-01-30 19:44
If you go to https://webcatalog.io, you'd see I'm rebuilding the app. It would fix this problem. :)

**Comment by vlad-cotfas** [comment] 2018-02-04 12:40
I`m having the same issue on Mac with WebCatalog 9.3.1 I can not update any App

**Comment by quanglam2807** [comment] 2018-02-08 16:45
I've removed the updater with the Appifier update.

**Closed as completed by quanglam2807** 2018-02-08 16:45 UTC
Labels: bug
